## Open Dayton Data Exploration - Litter Bin Data
Author: Amah Martin \
Description: Jupyter notebook that imports litter bin data and provides an overview of the data set.

In [2]:
import duckdb
duckdb.sql("INSTALL spatial; LOAD spatial;")

In [3]:
import pandas as pd

In [11]:
import requests

url = 'https://services2.arcgis.com/3dDB2Kk6kuA2gIGw/arcgis/rest/services/Litter_container/FeatureServer/0/query?where=1%3D1&outFields=*&f=geojson&resultRecordCount=500' 
r = requests.get(url)

with open('litter.geojson', 'w') as f:
    f.write(r.text)

In [4]:
df = duckdb.sql("""
SELECT * FROM ST_Read('litter.geojson')
""").df()

In [3]:
df.head()

,OGC_FID,ObjectID,Address,GlobalID,Condition,Rust,Door,Topper,Needs_Painting,Completed,geom
0,1,1,3201 N Main St,49d9f08b-556d-4ad5-b193-01407c51f6d8,NaN,NaN,NaN,NaN,NaN,No,"[1, 1, 0, 0, 0, 179, 34, 14, 208, 212, 13, 85,..."
1,2,2,1823 N Main St,6b32f68d-fd8b-4e3f-8e65-45778d5783be,NaN,NaN,NaN,NaN,NaN,No,"[1, 1, 0, 0, 0, 202, 111, 241, 212, 52, 13, 85..."
2,3,3,2315 N Main St,cbaa1e62-aac5-43af-ae2b-c16a078550f1,NaN,NaN,NaN,NaN,NaN,No,"[1, 1, 0, 0, 0, 102, 14, 217, 248, 126, 13, 85..."
3,4,4,2332 N Main St,6eb6a1a2-b50b-491e-b24d-19c958857307,NaN,NaN,NaN,NaN,NaN,No,"[1, 1, 0, 0, 0, 174, 126, 110, 239, 125, 13, 8..."
4,5,5,500 Salem Ave,7b0c4325-5443-4810-b955-b0ae75bb54c3,NaN,NaN,NaN,NaN,NaN,No,"[1, 1, 0, 0, 0, 34, 82, 211, 252, 124, 13, 85,..."

In [4]:
df.shape

(424, 11)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 424 entries, 0 to 423
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   OGC_FID         424 non-null    int64
 1   ObjectID        424 non-null    int32
 2   Address         424 non-null    str
 3   GlobalID        424 non-null    str
 4   Condition       206 non-null    str
 5   Rust            206 non-null    str
 6   Door            206 non-null    str
 7   Topper          206 non-null    str
 8   Needs_Painting  206 non-null    str
 9   Completed       424 non-null    str
 10  geom            416 non-null    object
dtypes: int32(1), int64(1), object(1), str(8)
memory usage: 34.9+ KB

In [7]:
df.tail()

,OGC_FID,ObjectID,Address,GlobalID,Condition,Rust,Door,Topper,Needs_Painting,Completed,geom
419,492,492,118 E First St,bab74d6e-6378-4de9-b04f-0bf7142105f1,Fair,No,Good,Good,No,Yes,"[1, 1, 0, 0, 0, 65, 154, 246, 78, 42, 12, 85, ..."
420,493,493,136 N Saint Clair St,bdcadfea-7552-4340-91f1-249358b4fb78,Fair,Yes,Good,Good,Yes,Yes,"[1, 1, 0, 0, 0, 231, 224, 6, 56, 21, 12, 85, 1..."
421,494,494,36 N Ludlow St,07db1fb2-9770-404b-b483-6bb7f6140ac8,Poor,Yes,Good,Bad,Yes,Yes,"[1, 1, 0, 0, 0, 240, 92, 246, 230, 101, 12, 85..."
422,495,495,110 S Jefferson St,e5ef0c66-b62e-4fe0-82a2-f0daf94989e2,Good,No,Good,Good,No,Yes,"[1, 1, 0, 0, 0, 34, 98, 183, 203, 32, 12, 85, ..."
423,496,496,35 S Jefferson St,3314b631-1220-4caf-b3c9-e076fcde6c40,Fair,No,Good,Good,No,Yes,"[1, 1, 0, 0, 0, 123, 104, 81, 37, 39, 12, 85, ..."

In [27]:
df.describe(include='object')

/tmp/ipykernel_114539/87514550.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include='object')

,Address,GlobalID,Condition,Rust,Door,Topper,Needs_Painting,Completed,geom
count,424,424,206,206,206,206,206,424,416
unique,403,424,3,2,2,2,2,2,415
top,110 N Ludlow St,49d9f08b-556d-4ad5-b193-01407c51f6d8,Fair,Yes,Good,Bad,Yes,No,"[1, 1, 0, 0, 0, 228, 150, 216, 99, 109, 14, 85..."
freq,5,1,75,125,170,109,157,218,2

In [29]:
for col in df:
    print(f"{df[col].value_counts()}\n")

OGC_FID
1      1
2      1
3      1
4      1
5      1
      ..
492    1
493    1
494    1
495    1
496    1
Name: count, Length: 424, dtype: int64

ObjectID
1      1
2      1
3      1
4      1
5      1
      ..
492    1
493    1
494    1
495    1
496    1
Name: count, Length: 424, dtype: int64

Address
110 N Ludlow St         5
2350 Catalpa Ave        2
220 E Monument Ave      2
200 E Second St         2
110 S Jefferson St      2
                       ..
44 N Jefferson St       1
118 E First St          1
136 N Saint Clair St    1
36 N Ludlow St          1
35 S Jefferson St       1
Name: count, Length: 403, dtype: int64

GlobalID
49d9f08b-556d-4ad5-b193-01407c51f6d8    1
6b32f68d-fd8b-4e3f-8e65-45778d5783be    1
cbaa1e62-aac5-43af-ae2b-c16a078550f1    1
6eb6a1a2-b50b-491e-b24d-19c958857307    1
7b0c4325-5443-4810-b955-b0ae75bb54c3    1
                                       ..
bab74d6e-6378-4de9-b04f-0bf7142105f1    1
bdcadfea-7552-4340-91f1-249358b4fb78    1
07db1fb2-9770-404b-b483-6bb7f6140ac8    1
e5ef0c66-b62e-4fe0-82a2-f0daf94989e2    1
3314b631-1220-4caf-b3c9-e076fcde6c40    1
Name: count, Length: 424, dtype: int64

Condition
Fair    75
Good    69
Poor    62
Name: count, dtype: int64

Rust
Yes    125
No      81
Name: count, dtype: int64

Door
Good    170
Bad      36
Name: count, dtype: int64

Topper
Bad     109
Good     97
Name: count, dtype: int64

Needs_Painting
Yes    157
No      49
Name: count, dtype: int64

Completed
No     218
Yes    206
Name: count, dtype: int64

geom
[1, 1, 0, 0, 0, 228, 150, 216, 99, 109, 14, 85, 192, 215, 135, 32, 46, 53, 229, 67, 64]      2
[1, 1, 0, 0, 0, 179, 34, 14, 208, 212, 13, 85, 192, 138, 76, 220, 137, 173, 229, 67, 64]     1
[1, 1, 0, 0, 0, 202, 111, 241, 212, 52, 13, 85, 192, 237, 186, 164, 64, 204, 227, 67, 64]    1
[1, 1, 0, 0, 0, 102, 14, 217, 248, 126, 13, 85, 192, 93, 188, 129, 245, 125, 228, 67, 64]    1
[1, 1, 0, 0, 0, 174, 126, 110, 239, 125, 13, 85, 192, 129, 43, 137, 29, 155, 228, 67, 64]    1
                                                                                            ..
[1, 1, 0, 0, 0, 65, 154, 246, 78, 42, 12, 85, 192, 129, 148, 60, 5, 158, 225, 67, 64]        1
[1, 1, 0, 0, 0, 231, 224, 6, 56, 21, 12, 85, 192, 185, 59, 25, 241, 146, 225, 67, 64]        1
[1, 1, 0, 0, 0, 240, 92, 246, 230, 101, 12, 85, 192, 104, 33, 174, 240, 75, 225, 67, 64]     1
[1, 1, 0, 0, 0, 34, 98, 183, 203, 32, 12, 85, 192, 138, 187, 145, 181, 15, 225, 67, 64]      1
[1, 1, 0, 0, 0, 123, 104, 81, 37, 39, 12, 85, 192, 241, 230, 192, 81, 32, 225, 67, 64]       1
Name: count, Length: 415, dtype: int64

In [32]:
for col in df:
    print(col)
    print(f"{df[col].unique()}\n")

OGC_FID
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  60  61  62  63  64  65  67  68  69  70  71  72  73  74
  75  76  77  78  79  80  81  82  83  84  85  86  87  90  91  92  93  94
  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111 112
 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130
 131 132 133 134 135 136 137 138 139 140 141 142 143 145 147 148 149 150
 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168
 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186
 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 203 204 205
 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223
 224 225 226 227 228 229 231 235 236 238 239 241 242 243 244 245 249 250
 251 252 253 254 255 256 257 258 259 261 263 264 265 268 269 271 272 273
 275 277 278 279 280 281 282 284 285 286 288 289 290 291 292 293 294 295
 296 298 299 300 301 302 303 304 305 306 307 309 311 313 314 316 317 318
 319 320 321 322 323 324 325 326 327 330 331 332 333 334 335 336 337 339
 340 341 342 343 344 345 346 348 349 350 351 352 353 354 355 356 357 359
 360 364 366 367 368 369 371 373 375 378 379 380 382 384 385 387 388 389
 390 391 392 395 397 398 399 402 403 404 406 407 408 410 414 415 416 418
 419 420 421 422 423 424 426 427 428 429 430 431 432 433 434 436 437 438
 448 449 450 451 452 453 454 455 456 457 459 460 461 462 463 464 465 466
 467 468 469 472 473 474 475 476 477 478 479 480 481 482 483 484 485 486
 487 488 489 490 491 492 493 494 495 496]

ObjectID
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  60  61  62  63  64  65  67  68  69  70  71  72  73  74
  75  76  77  78  79  80  81  82  83  84  85  86  87  90  91  92  93  94
  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111 112
 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130
 131 132 133 134 135 136 137 138 139 140 141 142 143 145 147 148 149 150
 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168
 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186
 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 203 204 205
 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223
 224 225 226 227 228 229 231 235 236 238 239 241 242 243 244 245 249 250
 251 252 253 254 255 256 257 258 259 261 263 264 265 268 269 271 272 273
 275 277 278 279 280 281 282 284 285 286 288 289 290 291 292 293 294 295
 296 298 299 300 301 302 303 304 305 306 307 309 311 313 314 316 317 318
 319 320 321 322 323 324 325 326 327 330 331 332 333 334 335 336 337 339
 340 341 342 343 344 345 346 348 349 350 351 352 353 354 355 356 357 359
 360 364 366 367 368 369 371 373 375 378 379 380 382 384 385 387 388 389
 390 391 392 395 397 398 399 402 403 404 406 407 408 410 414 415 416 418
 419 420 421 422 423 424 426 427 428 429 430 431 432 433 434 436 437 438
 448 449 450 451 452 453 454 455 456 457 459 460 461 462 463 464 465 466
 467 468 469 472 473 474 475 476 477 478 479 480 481 482 483 484 485 486
 487 488 489 490 491 492 493 494 495 496]

Address
<StringArray>
[      '3201 N Main St',       '1823 N Main St',       '2315 N Main St',
       '2332 N Main St',        '500 Salem Ave',        '627 Salem Ave',
        '340 Salem Ave',        '301 Salem Ave',        '628 Salem Ave',
       '1702 Salem Ave',
 ...
           '6 Gates St',          '14 Gates St',        '329 Wayne Ave',
        '415 Wayne Ave',      '111 E Fourth St',    '44 N Jefferson St',
       '118 E First St', '136 N Saint Clair St',       '36 N Ludlow St',
    '35 S Jefferson St']
Length: 403, dtype: str

GlobalID
<StringArray>
['49d9f08b-556d-4ad5-b193-01407c51f6d8',
 '6b32f68d-fd8b-4e3f-8e65-45778d5783be',
 'cbaa1e62-aac5-43af-ae2b-c16a078550f1',
 '6eb6a1a2-b50b-491e-b24d-19c958857307',
 '7b0c4325-5443-4810-b955-b0ae75bb54c3',
 'cdd1dea5-e3b1-457b-bf07-39e786661f47',
 '7f84090e-629b-4282-8d6d-e11c5d967f8c',
 'e3de244a-7162-4f4a-b3e8-f716d3576aed',
 'a39db7a4-9eb9-49c8-8deb-f10e60bc2315',
 '75c8ffca-7829-49cb-b57f-36bf854fe827',
 ...
 'b190a3c7-c9ad-41a7-8ad7-64f482ca30d3',
 'bed53dd0-c5e9-434d-a427-45c53bb28faf',
 '6f83d6da-9e85-46a1-bd8c-a2381e166a5a',
 '27f5744b-aff5-4f98-aac0-a6ab266a153e',
 '32588291-9ae7-408d-a47f-a72751c3b37b',
 'bab74d6e-6378-4de9-b04f-0bf7142105f1',
 'bdcadfea-7552-4340-91f1-249358b4fb78',
 '07db1fb2-9770-404b-b483-6bb7f6140ac8',
 'e5ef0c66-b62e-4fe0-82a2-f0daf94989e2',
 '3314b631-1220-4caf-b3c9-e076fcde6c40']
Length: 424, dtype: str

Condition
<StringArray>
[nan, 'Good', 'Poor', 'Fair']
Length: 4, dtype: str

Rust
<StringArray>
[nan, 'No', 'Yes']
Length: 3, dtype: str

Door
<StringArray>
[nan, 'Good', 'Bad']
Length: 3, dtype: str

Topper
<StringArray>
[nan, 'Good', 'Bad']
Length: 3, dtype: str

Needs_Painting
<StringArray>
[nan, 'No', 'Yes']
Length: 3, dtype: str

Completed
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

geom

TypeError: unhashable type: 'bytearray'

Notes:
- Half the rows have missing data for condition fields

In [36]:
for col in df:
    print(f"{df[col].value_counts(normalize=True) * 100}\n")

OGC_FID
1      0.235849
2      0.235849
3      0.235849
4      0.235849
5      0.235849
         ...
492    0.235849
493    0.235849
494    0.235849
495    0.235849
496    0.235849
Name: proportion, Length: 424, dtype: float64

ObjectID
1      0.235849
2      0.235849
3      0.235849
4      0.235849
5      0.235849
         ...
492    0.235849
493    0.235849
494    0.235849
495    0.235849
496    0.235849
Name: proportion, Length: 424, dtype: float64

Address
110 N Ludlow St         1.179245
2350 Catalpa Ave        0.471698
220 E Monument Ave      0.471698
200 E Second St         0.471698
110 S Jefferson St      0.471698
                          ...
44 N Jefferson St       0.235849
118 E First St          0.235849
136 N Saint Clair St    0.235849
36 N Ludlow St          0.235849
35 S Jefferson St       0.235849
Name: proportion, Length: 403, dtype: float64

GlobalID
49d9f08b-556d-4ad5-b193-01407c51f6d8    0.235849
6b32f68d-fd8b-4e3f-8e65-45778d5783be    0.235849
cbaa1e62-aac5-43af-ae2b-c16a078550f1    0.235849
6eb6a1a2-b50b-491e-b24d-19c958857307    0.235849
7b0c4325-5443-4810-b955-b0ae75bb54c3    0.235849
                                          ...
bab74d6e-6378-4de9-b04f-0bf7142105f1    0.235849
bdcadfea-7552-4340-91f1-249358b4fb78    0.235849
07db1fb2-9770-404b-b483-6bb7f6140ac8    0.235849
e5ef0c66-b62e-4fe0-82a2-f0daf94989e2    0.235849
3314b631-1220-4caf-b3c9-e076fcde6c40    0.235849
Name: proportion, Length: 424, dtype: float64

Condition
Fair    36.407767
Good    33.495146
Poor    30.097087
Name: proportion, dtype: float64

Rust
Yes    60.679612
No     39.320388
Name: proportion, dtype: float64

Door
Good    82.524272
Bad     17.475728
Name: proportion, dtype: float64

Topper
Bad     52.912621
Good    47.087379
Name: proportion, dtype: float64

Needs_Painting
Yes    76.213592
No     23.786408
Name: proportion, dtype: float64

Completed
No     51.415094
Yes    48.584906
Name: proportion, dtype: float64

geom
[1, 1, 0, 0, 0, 228, 150, 216, 99, 109, 14, 85, 192, 215, 135, 32, 46, 53, 229, 67, 64]      0.480769
[1, 1, 0, 0, 0, 179, 34, 14, 208, 212, 13, 85, 192, 138, 76, 220, 137, 173, 229, 67, 64]     0.240385
[1, 1, 0, 0, 0, 202, 111, 241, 212, 52, 13, 85, 192, 237, 186, 164, 64, 204, 227, 67, 64]    0.240385
[1, 1, 0, 0, 0, 102, 14, 217, 248, 126, 13, 85, 192, 93, 188, 129, 245, 125, 228, 67, 64]    0.240385
[1, 1, 0, 0, 0, 174, 126, 110, 239, 125, 13, 85, 192, 129, 43, 137, 29, 155, 228, 67, 64]    0.240385
                                                                                               ...
[1, 1, 0, 0, 0, 65, 154, 246, 78, 42, 12, 85, 192, 129, 148, 60, 5, 158, 225, 67, 64]        0.240385
[1, 1, 0, 0, 0, 231, 224, 6, 56, 21, 12, 85, 192, 185, 59, 25, 241, 146, 225, 67, 64]        0.240385
[1, 1, 0, 0, 0, 240, 92, 246, 230, 101, 12, 85, 192, 104, 33, 174, 240, 75, 225, 67, 64]     0.240385
[1, 1, 0, 0, 0, 34, 98, 183, 203, 32, 12, 85, 192, 138, 187, 145, 181, 15, 225, 67, 64]      0.240385
[1, 1, 0, 0, 0, 123, 104, 81, 37, 39, 12, 85, 192, 241, 230, 192, 81, 32, 225, 67, 64]       0.240385
Name: proportion, Length: 415, dtype: float64

In [37]:
print(df.isnull().sum())

OGC_FID             0
ObjectID            0
Address             0
GlobalID            0
Condition         218
Rust              218
Door              218
Topper            218
Needs_Painting    218
Completed           0
geom                8
dtype: int64

In [ ]:
print((df.isnull().sum() / len(df) * 100).round(1))

OGC_FID            0.0
ObjectID           0.0
Address            0.0
GlobalID           0.0
Condition         51.4
Rust              51.4
Door              51.4
Topper            51.4
Needs_Painting    51.4
Completed          0.0
geom               1.9
dtype: float64

In [6]:
print(df['Condition'].notna().sum(), 'inspected out of', len(df))

206 inspected out of 424

In [7]:
for col in ['Condition', 'Rust', 'Door', 'Topper', 'Needs_Painting', 'Completed']:
       print(f"{col}: {df[col].value_counts(dropna=False).to_dict()}")

Condition: {nan: 218, 'Fair': 75, 'Good': 69, 'Poor': 62}
Rust: {nan: 218, 'Yes': 125, 'No': 81}
Door: {nan: 218, 'Good': 170, 'Bad': 36}
Topper: {nan: 218, 'Bad': 109, 'Good': 97}
Needs_Painting: {nan: 218, 'Yes': 157, 'No': 49}
Completed: {'No': 218, 'Yes': 206}

In [8]:
print('Unique addresses:', df['Address'].nunique())

Unique addresses: 403

In [12]:
for col in ['Rust', 'Door', 'Topper', 'Needs_Painting']:
       print(f"\n{col} by Condition:")
       print(pd.crosstab(df['Condition'], df[col], margins=True))

Rust by Condition:
Rust       No  Yes  All
Condition
Fair       20   55   75
Good       59   10   69
Poor        2   60   62
All        81  125  206

Door by Condition:
Door       Bad  Good  All
Condition
Fair         2    73   75
Good         1    68   69
Poor        33    29   62
All         36   170  206

Topper by Condition:
Topper     Bad  Good  All
Condition
Fair        39    36   75
Good        13    56   69
Poor        57     5   62
All        109    97  206

Needs_Painting by Condition:
Needs_Painting  No  Yes  All
Condition
Fair             6   69   75
Good            42   27   69
Poor             1   61   62
All             49  157  206

In [13]:
pd.crosstab(df['Condition'], [df['Rust'], df['Door'], df['Topper'], df['Needs_Painting']])

Rust            No                            Yes
Door           Bad          Good              Bad      Good
Topper         Bad     Good  Bad     Good     Bad Good  Bad Good
Needs_Painting  No Yes   No   No Yes   No Yes Yes  Yes  Yes  Yes
Condition
Fair             0   0    0    1   3    5  11   2    0   33   20
Good             0   0    1    1  10   40   7   0    0    2    8
Poor             1   1    0    0   0    0   0  30    1   25    4

In [5]:
for col in ['Rust', 'Door', 'Topper', 'Needs_Painting']:
       print(f"\n{col} by Completed:")
       print(pd.crosstab(df['Completed'], df[col], margins=True))

Rust by Completed:
Rust       No  Yes  All
Completed
Yes        81  125  206
All        81  125  206

Door by Completed:
Door       Bad  Good  All
Completed
Yes         36   170  206
All         36   170  206

Topper by Completed:
Topper     Bad  Good  All
Completed
Yes        109    97  206
All        109    97  206

Needs_Painting by Completed:
Needs_Painting  No  Yes  All
Completed
Yes             49  157  206
All             49  157  206

In [6]:
df['Completed'].value_counts()

Completed
No     218
Yes    206
Name: count, dtype: int64

In [14]:
for col in ['Rust', 'Door', 'Topper', 'Needs_Painting']:
       print(f"{df.pivot_table(index='Completed', columns=col, aggfunc='size', fill_value=0, dropna=False)}\n")

Rust       No  Yes  NaN
Completed
No          0    0  218
Yes        81  125    0

Door       Bad  Good  NaN
Completed
No           0     0  218
Yes         36   170    0

Topper     Bad  Good  NaN
Completed
No           0     0  218
Yes        109    97    0

Needs_Painting  No  Yes  NaN
Completed
No               0    0  218
Yes             49  157    0

In [20]:
df.groupby('Completed')['GlobalID'].count()

Completed
No     218
Yes    206
Name: GlobalID, dtype: int64

Note: Completed represents completed inspection. Evidence based on non-null values of condition fields (rust, topper, door, etc.) as well as reviewing map source data showing locations with completed data fields and photos.